#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("XamarinJsonSiteTest.Resource", IsApplication=true)]

namespace XamarinJsonSiteTest
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040004
			public const int email = 2130968580;
			
			// aapt resource value: 0x7f04000d
			public const int forgot_password_underline = 2130968589;
			
			// aapt resource value: 0x7f040008
			public const int image_remember_wrapper = 2130968584;
			
			// aapt resource value: 0x7f04000b
			public const int login = 2130968587;
			
			// aapt resource value: 0x7f040000
			public const int login_background = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int logo = 2130968578;
			
			// aapt resource value: 0x7f040006
			public const int password = 2130968582;
			
			// aapt resource value: 0x7f040005
			public const int password_background = 2130968581;
			
			// aapt resource value: 0x7f040009
			public const int remember_me_image = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int remember_me_text = 2130968586;
			
			// aapt resource value: 0x7f040007
			public const int remember_me_touch_area = 2130968583;
			
			// aapt resource value: 0x7f040001
			public const int root_view = 2130968577;
			
			// aapt resource value: 0x7f04000c
			public const int text_view_forgot_password = 2130968588;
			
			// aapt resource value: 0x7f040003
			public const int username_background = 2130968579;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f020000
			public const int Login = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Main = 2130837505;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030000
			public const int app_name = 2130903040;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
